-- 剧本杀门店运营管理系统：初始化脚本（PostgreSQL，由 docker-entrypoint-initdb.d 自动执行）
-- 场次开始时间以门店统一时区（东八区）墙钟存储为 TIMESTAMP，
-- 固定初始化会话时区，保证 CURRENT_TIMESTAMP 灌入的种子时间也是门店墙钟。
SET TIME ZONE 'Asia/Shanghai';

-- 运营总览（既有模块）
CREATE TABLE IF NOT EXISTS operation_records (
  id SERIAL PRIMARY KEY,
  module_name VARCHAR(120) NOT NULL,
  owner_name VARCHAR(80) NOT NULL,
  status VARCHAR(40) NOT NULL,
  metric VARCHAR(40) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO operation_records (module_name, owner_name, status, metric)
SELECT '剧本库与DM管理', '运营组', 'ready', '100%'
WHERE NOT EXISTS (SELECT 1 FROM operation_records);

-- 剧本库
CREATE TABLE IF NOT EXISTS scripts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  genre VARCHAR(60) NOT NULL,
  difficulty VARCHAR(20) NOT NULL,
  duration_minutes INTEGER NOT NULL,
  min_players INTEGER NOT NULL,
  max_players INTEGER NOT NULL,
  dm_required BOOLEAN NOT NULL DEFAULT TRUE,
  description VARCHAR(500),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 玩家（会员）
CREATE TABLE IF NOT EXISTS players (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  phone VARCHAR(30) NOT NULL UNIQUE,
  member_level VARCHAR(20) NOT NULL DEFAULT '青铜',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 场次：门店排期。status: SCHEDULED 报名中 / STARTED 已开始 / CANCELLED 已取消
CREATE TABLE IF NOT EXISTS sessions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  script_id BIGINT NOT NULL REFERENCES scripts(id),
  dm_name VARCHAR(80),
  start_time TIMESTAMP NOT NULL,
  capacity INTEGER NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_sessions_status_start ON sessions (status, start_time);

-- 报名记录：status: REGISTERED 已报名(占名额) / WAITLISTED 候补中 / CANCELLED 已取消
CREATE TABLE IF NOT EXISTS registrations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id BIGINT NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
  player_id BIGINT NOT NULL REFERENCES players(id),
  status VARCHAR(20) NOT NULL,
  waitlist_position INTEGER,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  -- 同一玩家在同一场次只有一行记录：取消后该行置为 CANCELLED，再次报名复用，
  -- 因此任意时刻最多只有一条有效报名（REGISTERED/WAITLISTED）
  UNIQUE (session_id, player_id)
);
CREATE INDEX IF NOT EXISTS idx_registrations_session_status
  ON registrations (session_id, status, waitlist_position);

-- ---------- 种子数据 ----------
INSERT INTO scripts (id, name, genre, difficulty, duration_minutes, min_players, max_players, dm_required, description) VALUES
  (1, '年轮', '情感还原', '困难', 300, 4, 6, TRUE, '跨时空情感还原本，层层反转，适合熟车体验。'),
  (2, '窗边的女人', '推理硬核', '中等', 240, 5, 7, TRUE, '本格推理本，重证据链与时间线，适合推理爱好者。'),
  (3, '欢乐大富翁', '欢乐机制', '简单', 180, 6, 8, FALSE, '轻松欢乐机制本，新人友好，适合团建拼车。'),
  (4, '雾起云浮', '恐怖沉浸', '困难', 300, 4, 6, TRUE, '沉浸式恐怖本，氛围拉满，胆大者入。'),
  (5, '星夜双人舞', '情感还原', '中等', 180, 2, 8, TRUE, '支持双人开场的灵活拼车本，小团也能开。');

INSERT INTO players (id, name, phone, member_level) VALUES
  (1, '林晓彤', '13800000001', '黄金'),
  (2, '陈志远', '13800000002', '白银'),
  (3, '苏婉清', '13800000003', '青铜'),
  (4, '赵启铭', '13800000004', '钻石'),
  (5, '周沐沐', '13800000005', '白银'),
  (6, '何子昂', '13800000006', '青铜');

-- 场次A：明天开场，名额6，已报4人（余2）
INSERT INTO sessions (id, script_id, dm_name, start_time, capacity, status)
VALUES (1, 2, 'DM 老柯', CURRENT_TIMESTAMP + INTERVAL '1 day', 6, 'SCHEDULED');
-- 场次B：后天开场，名额4，已满员且有2人候补
INSERT INTO sessions (id, script_id, dm_name, start_time, capacity, status)
VALUES (2, 1, 'DM 小鹿', CURRENT_TIMESTAMP + INTERVAL '2 day', 4, 'SCHEDULED');
-- 场次C：3小时后开场，名额8，无人报名
INSERT INTO sessions (id, script_id, dm_name, start_time, capacity, status)
VALUES (3, 3, NULL, CURRENT_TIMESTAMP + INTERVAL '3 hour', 8, 'SCHEDULED');
-- 场次D：昨天已开场（已开始状态，不可报名）
INSERT INTO sessions (id, script_id, dm_name, start_time, capacity, status)
VALUES (4, 4, 'DM 老柯', CURRENT_TIMESTAMP - INTERVAL '1 day', 6, 'STARTED');

INSERT INTO registrations (session_id, player_id, status, waitlist_position) VALUES
  (1, 1, 'REGISTERED', NULL),
  (1, 2, 'REGISTERED', NULL),
  (1, 3, 'REGISTERED', NULL),
  (1, 4, 'REGISTERED', NULL),
  (2, 1, 'REGISTERED', NULL),
  (2, 2, 'REGISTERED', NULL),
  (2, 5, 'REGISTERED', NULL),
  (2, 6, 'REGISTERED', NULL),
  (2, 3, 'WAITLISTED', 1),
  (2, 4, 'WAITLISTED', 2);

-- 显式插入种子 ID 后，把序列推到种子范围之上，避免后续插入主键冲突
ALTER SEQUENCE scripts_id_seq RESTART WITH 100;
ALTER SEQUENCE players_id_seq RESTART WITH 100;
ALTER SEQUENCE sessions_id_seq RESTART WITH 100;
ALTER SEQUENCE registrations_id_seq RESTART WITH 100;
